# Generated by Django 4.1.3 on 2022-11-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=50, unique=True, verbose_name='Desease Code')),
                ('pathogen', models.CharField(max_length=20, verbose_name='Pathogen')),
                ('description', models.CharField(max_length=140, verbose_name='Description')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_type.diseasetype')),
            ],
        ),
    ]
