# Generated by Django 4.1.3 on 2022-11-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease_type', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_enc_date', models.DateTimeField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_type.diseasetype')),
            ],
        ),
    ]
