# Generated by Django 4.1.3 on 2022-11-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_alter_discover_first_enc_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discover',
            name='first_enc_date',
        ),
        migrations.AddField(
            model_name='discover',
            name='first_enc_date_day',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='discover',
            name='first_enc_date_month',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='discover',
            name='first_enc_date_year',
            field=models.PositiveIntegerField(default=2022),
        ),
    ]
