# Generated by Django 4.1.3 on 2022-11-16 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('surname', models.CharField(max_length=40, unique=True, verbose_name='Surname')),
                ('salary', models.PositiveBigIntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
        ),
    ]
