# Generated by Django 4.1.3 on 2022-11-17 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('publicservant', '0001_initial'),
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deaths', models.PositiveBigIntegerField(default=0)),
                ('total_patients', models.PositiveBigIntegerField(default=0)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.disease')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicservant.publicservant')),
            ],
        ),
    ]
