# Generated by Django 4.1.3 on 2022-11-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=65, unique=True, verbose_name='Country Name')),
                ('population', models.PositiveBigIntegerField(verbose_name='Population')),
            ],
        ),
    ]
